Create test machine with less cores to run ebpf unit tests.
This change is to fix failure in creating the test VM.
```
+ gcloud compute instances create \
prow-1645843847701336064-2023-04-11-10-39-40-af33a5-ttl1d \
--project gke-anthos-datapath-presubmits --zone us-west1-b \
--enable-nested-virtualization \
--metadata-from-file=startup-script=./google_test/countdown-and-self-destruct.sh \
--image-project=cos-cloud --image-family=cos-97-lts \
--machine-type=n2-highcpu-32 --boot-disk-size=256GB

WARNING: Some requests generated warnings:
 - Disk size: '256 GB' is larger than image size: '10 GB'.
You might need to resize the root repartition manually if the
operating system does not support automatic resizing. See
https://cloud.google.com/compute/docs/disks/add-persistent-disk#resize_pd
for details.

ERROR: (gcloud.compute.instances.create) Could not fetch resource:
 - Quota 'N2_CPUS' exceeded.  Limit: 300.0 in region us-west1.
	metric name = compute.googleapis.com/n2_cpus
	limit name = N2-CPUS-per-project-region
	dimensions = region: us-west1
Try your request in another zone, or view documentation on how to
increase quotas: https://cloud.google.com/compute/quotas.
```

Bug: 275574332
Change-Id: I643043dd8df48f3567ba2374e6e050ed20f0d482
Reviewed-on: https://gke-internal-review.googlesource.com/c/third_party/cilium/+/670303
Unit-Verified: Prow_Bot_V2 <425329972751-compute@developer.gserviceaccount.com>
Reviewed-by: Paulo Castello da Costa <pcastello@google.com>

Use the machine n2-highcpu-2 to run ebpf unit tests

Consult `gcloud compute machine-types list --zones us-west1-b` to
see the available machine types.

```
NAME              ZONE        CPUS  MEMORY_GB  DEPRECATED
n2-highcpu-16     us-west1-b  16    16.00
n2-highcpu-2      us-west1-b  2     2.00
n2-highcpu-32     us-west1-b  32    32.00
n2-highcpu-4      us-west1-b  4     4.00
n2-highcpu-48     us-west1-b  48    48.00
n2-highcpu-64     us-west1-b  64    64.00
n2-highcpu-8      us-west1-b  8     8.00
```

Change-Id: I28a4e9cb0e92d06f870491dd9aea0d14e9a0a708
Reviewed-on: https://gke-internal-review.googlesource.com/c/third_party/cilium/+/671281
Reviewed-by: Paulo Castello da Costa <pcastello@google.com>
Unit-Verified: Prow_Bot_V2 <425329972751-compute@developer.gserviceaccount.com>
Reviewed-on: https://gke-internal-review.googlesource.com/c/third_party/cilium/+/671740
Unit-Verified: Yongkun Gui <ygui@google.com>